### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by DeanHerbertPeppy** [NekosuServer/Nekosu-Client#2]
Discord rpc still uses ainu logo and text. will change in future when i find out how to do it, to anyone else in the orginization that knows how to edit this. hmu at @ Kaiser#1222 on discord xd.

**Comment by DeanHerbertPeppy** [comment]
nvm i figured it out with some help. issue CLOSED (bonk close)

**Comment by Mattyosu** [comment]
thats funny
